name: Github Action CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: ../../
